<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.0-SNAPSHOT</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece.plugins</groupId>
    <artifactId>plugin-kibana</artifactId>
    <packaging>lutece-plugin</packaging>
    <version>3.0.0-SNAPSHOT</version>
    <name>Lutece kibana plugin</name>
    <description>Provides Kibana dashboards</description>
    
    <repositories>
        <repository>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <id>luteceSnapshot</id>
            <name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
        </repository>
        <repository>
            <id>lutece</id>
            <name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>[8.0.0-SNAPSHOT,)</version>
            <type>lutece-core</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-httpaccess</artifactId>
            <version>[4.0.0-SNAPSHOT,)</version>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-elasticdata</artifactId>
            <version>[3.0.0-SNAPSHOT,)</version>
        </dependency> 
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20250517</version>
        </dependency>
        <dependency>
		    <groupId>fr.paris.lutece.plugins</groupId>
		    <artifactId>library-lutece-unit-testing</artifactId>
		    <type>jar</type>
		    <scope>test</scope>
		</dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <properties>
        <componentName>kibana</componentName>
    </properties>
    
    <scm>
        <connection>scm:git:https://github.com/lutece-platform/lutece-elk-plugin-kibana.git</connection>
        <developerConnection>scm:git:https://github.com/lutece-platform/lutece-elk-plugin-kibana.git</developerConnection>
        <url>https://github.com/lutece-platform/lutece-elk-plugin-kibana.git</url>
      <tag>HEAD</tag>
  </scm>
    
</project>